-- Sync fall_date from LifeCloud profiles
BEGIN;
UPDATE public.fallen_soldiers SET fall_date = '13.04.1948 - 03.09.1968 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/tuvia-tubias-shrikinger/';
UPDATE public.fallen_soldiers SET fall_date = '27.01.1952 - 10.01.1972 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yehoram-shiloni/';
UPDATE public.fallen_soldiers SET fall_date = '18.03.1998 - 26.10.2018 | טלמון', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yenon-yaron-yulis/';
UPDATE public.fallen_soldiers SET fall_date = '07.01.1998 - 26.07.2017 | נצרת עילית', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/ofek-klugman/';
UPDATE public.fallen_soldiers SET fall_date = '28.05.1978 - 09.06.1999 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/roi-keler/';
UPDATE public.fallen_soldiers SET fall_date = '01.01.1952 - 05.11.1976 | נווה אטיב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/naftali-khalfon/';
UPDATE public.fallen_soldiers SET fall_date = '25.10.1951 - 17.12.1972 | קרית ים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/moshe-poli-swartz/';
UPDATE public.fallen_soldiers SET fall_date = '14.11.1948 - 05.06.1967 | גבעת ברנר', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yoel-moshe-yoeli-shwartz/';
UPDATE public.fallen_soldiers SET fall_date = '03.11.1993 - 24.07.2012 | אשדוד', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/tal-segev/';
UPDATE public.fallen_soldiers SET fall_date = '05.05.1953 - 16.09.1972 | חיפה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/david-dudu-reler/';
UPDATE public.fallen_soldiers SET fall_date = '27.04.1954 - 12.10.1973 | נהריה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/mordehai-moti-rozen/';
UPDATE public.fallen_soldiers SET fall_date = '20.09.1985 - 08.01.2009 | ערד', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/omer-israel-rubinovitch/';
UPDATE public.fallen_soldiers SET fall_date = '10.07.1975 - 26.07.2006 | עלי', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/roi-klein/';
UPDATE public.fallen_soldiers SET fall_date = '13.07.1981 - 08.03.2002 | אשדוד', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/eduard-korol/';
UPDATE public.fallen_soldiers SET fall_date = '08.07.1947 - 14.07.1966 | נגב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/haim-aku-peretz/';
UPDATE public.fallen_soldiers SET fall_date = '29.06.1975 - 19.09.1996 | קדרון', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/tzur-prans/';
UPDATE public.fallen_soldiers SET fall_date = '22.05.1952 - 06.10.1973 | קרית ביאליק', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/ofir-planter/';
UPDATE public.fallen_soldiers SET fall_date = '01.09.1994 - 20.07.2006 | להב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yehonatan-sergei-fux-vlasiuk/';
UPDATE public.fallen_soldiers SET fall_date = '25.02.1980 - 29.03.2002 | קרית שמונה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/boaz-pomerantz/';
UPDATE public.fallen_soldiers SET fall_date = '22.10.1954 - 20.10.1973 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/reuven-politi/';
UPDATE public.fallen_soldiers SET fall_date = '30.05.1983 - 27.04.2007 | כרמיאל', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/amit-amran/';
UPDATE public.fallen_soldiers SET fall_date = '29.04.1985 - 20.07.2006 | קרית שמונה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/liran-saadia/';
UPDATE public.fallen_soldiers SET fall_date = '10.01.1940 - 10.06.1982 | רמת גן', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/haim-sela/';
UPDATE public.fallen_soldiers SET fall_date = '02.06.1977 - 04.02.1997 | הוד השרון', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/moshe-shiko-saban/';
UPDATE public.fallen_soldiers SET fall_date = '21.01.1981 - 20.12.2000 | קיבוץ ניר דוד', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/geva-meskin-yaakobi/';
UPDATE public.fallen_soldiers SET fall_date = '10.10.1975 - 19.09.1996 | קרית חיים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/zohar-mintz/';
UPDATE public.fallen_soldiers SET fall_date = '13.08.1952 - 24.02.1972 | פתח תקווה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/eliyahu-eli-mitelman/';
UPDATE public.fallen_soldiers SET fall_date = '21.08.1985 - 20.07.2006 | מזכרת בתיה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/refanel-baruh-muskal/';
UPDATE public.fallen_soldiers SET fall_date = '10.04.1983 - 07.05.2004 | בת ים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/denis-leminov/';
UPDATE public.fallen_soldiers SET fall_date = '10.08.1950 - 25.05.1970 | רמת גן', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/daniel-dani-liberti/';
UPDATE public.fallen_soldiers SET fall_date = '11.03.1953 - 19.05.1973 | טירת הכרמל', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/aziz-hai-levi/';
UPDATE public.fallen_soldiers SET fall_date = '28.08.1975 - 24.12.1996 | בני יהודה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yosef-yossi-levi/';
UPDATE public.fallen_soldiers SET fall_date = '28.03.1979 - 28.12.2001 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/erez-levi/';
UPDATE public.fallen_soldiers SET fall_date = '02.02.1981 - 20.12.2000 | מושב מישר', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/guy-leo/';
UPDATE public.fallen_soldiers SET fall_date = '03.10.1946 - 02.09.1970 | קיבוץ מסילות', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/itzhak-itzik-katz/';
UPDATE public.fallen_soldiers SET fall_date = '01.12.1949 - 04.07.1969 | חיפה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/israel-assi-cohen/';
UPDATE public.fallen_soldiers SET fall_date = '18.03.1993 - 21.07.2014 | ראשון לציון', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/tal-nissim-ifrah/';
UPDATE public.fallen_soldiers SET fall_date = '01.01.1950 - 09.02.1969 | נס ציונה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yehezkel-tuina/';
UPDATE public.fallen_soldiers SET fall_date = '12.09.1951 - 22.02.1970 | מושב אליכין', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/zion-harazi/';
UPDATE public.fallen_soldiers SET fall_date = '26.05.1995 - 10.11.2014 | קיבוץ אלונים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/sharon-chen/';
UPDATE public.fallen_soldiers SET fall_date = '01.02.1983 - 19.06.2002 | אור יהודה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/ariel-hai/';
UPDATE public.fallen_soldiers SET fall_date = '01.01.1949 - 30.04.1968 | מושב שער אפרים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/benyamin-benny-hadad/';
UPDATE public.fallen_soldiers SET fall_date = '04.05.1949 - 03.09.1968 | יבנאל', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/avraham-avramik-hameiri/';
UPDATE public.fallen_soldiers SET fall_date = '03.10.1979 - 20.07.2006 | רעננה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/benyamin-aharon-benji-hilman/';
UPDATE public.fallen_soldiers SET fall_date = '07.01.1950 - 03.11.1972 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yosef-dirhali/';
UPDATE public.fallen_soldiers SET fall_date = '07.01.1980 - 13.03.2003 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yoav-doron/';
UPDATE public.fallen_soldiers SET fall_date = '15.02.1992 - 21.07.2014 | כפר סבא', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yuval-yuvi-dagan/';
UPDATE public.fallen_soldiers SET fall_date = '26.02.1976 - 24.12.1996 | פתח תקווה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/nir-israel-gendelberg/';
UPDATE public.fallen_soldiers SET fall_date = '14.02.1951 - 10.09.1970 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/daniel-gurnitzki/';
UPDATE public.fallen_soldiers SET fall_date = '15.09.1951 - 07.01.1972 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/doron-golan-goldshtein/';
UPDATE public.fallen_soldiers SET fall_date = '16.11.1949 - 24.02.1972 | טבריה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/dror-drori-bergman/';
UPDATE public.fallen_soldiers SET fall_date = '01.01.1950 - 30.08.1970 | קיבוץ הזורע', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/amnon-emy-bar-ner/';
UPDATE public.fallen_soldiers SET fall_date = '19.04.1992 - 20.07.2014 | אשקלון', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/jordan-efraim-ben-simon/';
UPDATE public.fallen_soldiers SET fall_date = '28.09.1980 - 13.03.2003 | קרית ארבע', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yehuda-ben-yosef/';
UPDATE public.fallen_soldiers SET fall_date = '13.10.1954 - 06.10.1973 | פתח תקווה', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/matityahu-mati-ben-zeharia/';
UPDATE public.fallen_soldiers SET fall_date = '10.09.1987 - 09.04.2008 | כפר ג''את', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/sayef-bisan/';
UPDATE public.fallen_soldiers SET fall_date = '07.07.1985 - 20.07.2006 | כרמיאל', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/nada-balva/';
UPDATE public.fallen_soldiers SET fall_date = '13.02.1949 - 03.09.1968 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/yair-algarnati/';
UPDATE public.fallen_soldiers SET fall_date = '18.02.1983 - 19.06.2002 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/tzvi-yehuda-tziki-izman/';
UPDATE public.fallen_soldiers SET fall_date = '22.06.1950 - 31.01.1971 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/dov-dubi-adar/';
UPDATE public.fallen_soldiers SET fall_date = '01.08.1953 - 24.04.1974 | ירושלים', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/shalom-avital/';
UPDATE public.fallen_soldiers SET fall_date = '15.11.1982 - 26.07.2006 | עכו', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/alexander-sahsa-shwartzman/';
UPDATE public.fallen_soldiers SET fall_date = '22.12.1952 - 16.02.1974 | תל אביב', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/reuven-ayev-nissani/';
UPDATE public.fallen_soldiers SET fall_date = '20.08.1927 - 26.12.1956 | ג''וליס', updated_at = now() WHERE memorial_url = 'https://egoz.org.il/fallen/hassan-saliman-abu-najim/';
COMMIT;
